name: Add to OSS board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled

permissions:
  issues: read

jobs:

  run:
    uses: anchore/workflows/.github/workflows/oss-project-board-add.yaml@91139bea23527e94db5a1e9e9b77ad2975417930 # v0.2.0
    secrets:
      token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
