name: "Release"

permissions:
  contents: read
  checks: read

concurrency:
  group: release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      version:
        description: tag the latest commit on main with the given version (prefixed with v)
        required: true

jobs:

  version-available:
    uses: anchore/workflows/.github/workflows/check-version-available.yaml@91139bea23527e94db5a1e9e9b77ad2975417930 # v0.2.0
    with:
      version: ${{ github.event.inputs.version }}

  check-gate:
    uses: anchore/workflows/.github/workflows/check-gate.yaml@91139bea23527e94db5a1e9e9b77ad2975417930 # v0.2.0
    with:
      checks: '["Static analysis", "Unit tests"]'

  release:
    needs: [check-gate, version-available]
    environment: release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Create tag
        uses: anchore/workflows/.github/actions/create-tag-via-deploy-key@91139bea23527e94db5a1e9e9b77ad2975417930 # v0.2.0
        with:
          tag: ${{ github.event.inputs.version }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make ci-release RELEASE_VERSION=${{ github.event.inputs.version }}
